//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMiniVersion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookMiniVersion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_01 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_08 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_16 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_18 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_20 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_25 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_40 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_42 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_48 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_57 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_66 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TOON_XP_Icons__V1c__Icon_76 {
            get {
                object obj = ResourceManager.GetObject("TOON-XP Icons (V1c) Icon 76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
